### ISSUE TITLE
Following code along will not pass the tests

### ISSUE THREAD

**Issue by jappleba** [learn-co-curriculum/sinatra-password-security#10]
@SophieDeBenedetto... I am not 100% sure if I did something wrong, but I had to make a few minor adjustments to the code provided in the lab and in the instructions to get the tests passing. Again, not sure if this was an error on my end, but I think I followed the directions correctly. Probably worth looking into.

**Comment by AnnJohn** [comment]
Hi @jappleba could you let us know the specific adjustments you made? Thanks

**Comment by AnnJohn** [comment]
Reassigning this to @vicfriedman.

@jappleba could you let us know what specifically didn't work? thanks.

**Comment by AnnJohn** [comment]
Closing this issue
