### ISSUE TITLE
test database is here on github, get's cloned down

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sinatra-password-security#13]
from [this issue](https://github.com/learn-co-students/sinatra-password-security-web-1115/issues/4) raised by student in student repo: I know other people have completed this lab without this problem, so it's possible I did something wrong, but wanted to raise this issue. Upon initial cloning and trying to run 
from this issue raised by a student in student repo:
learn I received an error and was told to run rake db:migrate SINATRA_ENV=test. However, when I did so I received this error message:

SQLite3::SQLException: table "users" already exists: CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar, "password_digest" varchar) /Users/kaylee/.rvm/gems/ruby-2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'

(full stack trace not included as it was very long)

This happened even after deleting the repo and forking/cloning again, and no matter with order I ran rake db:migrate and rake db:migrate SINATRA_ENV=test in. The problem was eventually solved by deleting the following files: db/schema.rb and db/test.sqlite before running migrations.

Also, am not sure if the lab was intended to be just a codealong or if this was intentional, but several tests do not pass due to capybara not being able to find elements just as an FYI.

**Comment by vicfriedman** [comment]
removed db!
