### ISSUE TITLE
Issue with /spec/create_users_migration_spec.rb

### ISSUE THREAD

**Issue by jenjiyi** [learn-co-curriculum/sinatra-password-security#22]
'../db/migrate/20150916154312_create_users.rb'**'**

Needed to remove extra character to get tests to pass.

**Comment by tyleresmith** [comment]
Confirming that this issue still exists

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/sinatra-password-security/commit/24d81c8bb29447ddb604abd582e9362364180377
