### ISSUE TITLE
typo in spec file:    create_users_migration_spec.rb

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/sinatra-password-security#24]
There was an extra quotation mark ( ' ) at the end of the top line, causing the 'learn' command to fail.

original: 
require_relative '../db/migrate/20150916154312_create_users.rb''

edited: 
require_relative '../db/migrate/20150916154312_create_users.rb'

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/sinatra-password-security/commit/4e2c20eaa50e336ab730b0b2f5a51a434671050b
