### ISSUE TITLE
Shotgun not included in gemfile

### ISSUE THREAD

**Issue by sandyvern** [learn-co-curriculum/sinatra-password-security#26]
Get an error when attempt to run shotgun with this lab (error below)

`[18:55:37] (master) sinatra-password-security-v-000                                                                                              
// ♥ shotgun                                                                                                                                     
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in`require': cannot load such file -- rack/com
monlogger (LoadError)  
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'            
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in`require'  
        from /usr/local/rvm/gems/ruby-2.2.3/gems/shotgun-0.9.1/bin/shotgun:112:in `<top (required)>'                                             
        from /usr/local/rvm/gems/ruby-2.2.3/bin/shotgun:22:in`load'  
        from /usr/local/rvm/gems/ruby-2.2.3/bin/shotgun:22:in `<main>'`

I did attempt just add the shotgun gem to the gemfile and run bundle install again. Which did start up the server but when I viewed in my browser it gave me a boot error - problem with loading the config.ru file

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by ozPop** [comment]
This is still an ongoing problem.

In my case, once I added `gem "shotgun"` in the Gemfile and ran `bundle install` I was able to follow the readme and start `shotgun`.

**Comment by pickledyamsman** [comment]
@aturkewi This issue is still happening #29 looks like it would fix it. Just adding `gem "shotgun"` to the Gemfile also fixes it.

**Comment by aturkewi** [comment]
Fixed in PR #34
