### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by travislavery** [learn-co-curriculum/sinatra-password-security#40]
In this lab, if when in the CreateUsers migration file, if I used the more recent def change ... end syntax, the tests will not recognize that there is a users table. In the screenshots I changed absolutely nothing, except that in one I used the up/down syntax, in the other I used the change syntax. This is very frustrating as we have been taught that it makes no difference, in fact that it is recommended in an earlier lesson, to just use change. I had a pry command stop the flow of tests, to explain the screenshots further.
![errordata](https://user-images.githubusercontent.com/26154505/35179295-ed31b108-fd54-11e7-803c-52045cbe091a.PNG)
![errordata2](https://user-images.githubusercontent.com/26154505/35179296-ed4441ba-fd54-11e7-845d-b6bb05ad5fa5.PNG)
![errordata3](https://user-images.githubusercontent.com/26154505/35179297-ed5898e0-fd54-11e7-8906-45da75d4a4bd.PNG)

**Comment by maxwellbenton** [comment]
Hi there @travislavery ,

Thank you for submitting this feedback.  You are correct that `def change` is now the standard for migrations.  We're in the process of reviewing these labs and will likely rewrite this.  For now, though, we've added a note regarding `def up/down` vs `def change` for clarity.

As always, thanks for contributing! 💙
