### ISSUE TITLE
ActiveRecord version to be updated in the gemfile

### ISSUE THREAD

**Issue by purnima-nyc** [learn-co-curriculum/sinatra-password-security#46]
Bundler loads version 5.2 which raises the following error:

config.ru:3:in `block in <main>': undefined method `needs_migration?' for ActiveRecord::Migrator:Class (NoMethodError)

Update gemfile (as follows) to resolve the error- 
gem "activerecord", '<= 5.1'

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
