### ISSUE TITLE
needs_migration? no_method error

### ISSUE THREAD

**Issue by alcesalces11331** [learn-co-curriculum/sinatra-password-security#48]
if ActiveRecord::Migrator.needs_migration?

This line of code was throwing an error of no_method on the needs_migration? method when I was running my tests. I was able to comment out the code and have my tests pass, as I had already migrated SINATRA_ENV=test. 

However, it can be solved by updating the gemfile
gem "activerecord", '<= 5.1'

**Comment by cassaram09** [comment]
The problem is that the `needs_migration?` method has been removed from the ActiveRecord::Migrator class as of v5.1. We can fix this error by changing how we do the method call in `config.ru`.
```
if ActiveRecord::Base.connection.migration_context.needs_migration?
  raise 'Migrations are pending. Run `rake db:migrate` to resolve the issue.'
end
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
