### ISSUE TITLE
ActiveRecord version problems

### ISSUE THREAD

**Issue by mrfarmer777** [learn-co-curriculum/sinatra-password-security#49]
Worked through this issue on another lab this morning with tech coaches. In order to complete this lab, I had to revert back to ActiveRecord 4.2, change the inheritance in the class file (remove 5.2), change the gemfile, bundle install, and set everything up again. Not sure if this issue is happening with other labs, but it's worth fixing.

from migration file:
`class CreateUsers < ActiveRecord::Migration#[5.2]
  def up  
  end

  def down
  end
end`

gemfile
`source "https://rubygems.org"

gem "sinatra"
gem "activerecord", "4.2", :require => 'active_record' #<-----reverted back to activerecord 4.2
gem "sinatra-activerecord"
gem "rake"
gem "bcrypt"
gem "rspec"
gem "require_all"
gem "capybara"
gem "pry"
gem "sqlite3"
gem 'shotgun'

group :development do
  gem "tux"
end`

**Comment by FionaDL** [comment]
I agree that this is an issue. I worked through another lab to figure out this problem a few labs ago, am having the same issue with this lab.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
