### ISSUE TITLE
Need to comment out this code to make the lab work

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sinatra-password-security#52]
**You get the following error in this lab before you even type anything:**
NoMethodError:
  undefined method `migration_context' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007f99fdcb2d40>
  Did you mean?  migration_keys

**The solution is to comment out the following code in config.ru:**
# if ActiveRecord::Base.connection.migration_context.needs_migration?
#   raise 'Migrations are pending. Run `rake db:migrate` to resolve the issue.'
# end

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
