### ISSUE TITLE
Quick Fix- Missing Word "to" 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/sinatra-password-security#56]
2nd line from lesson below is missing word "to".   
************
We validate password match by using a method called authenticate on our User model. We do not have write this method ourselves. Rather when we added the line of code to User:

class User < ActiveRecord::Base
  has_secure_password
end
we told Ruby to add an authenticate method to our class (invisibly!) when the program runs. While we, as programmers can't see it, it will be there.
********************
Note: A minor thing, but want Flatiron to be all it can be! Thanks, Everyone.

**Comment by rrcobb** [comment]
Fixed in 0f7f241 , thanks for raising!
