### ISSUE TITLE
Quick Fix-Typo, Missing Word "to" 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/sinatra-password-security#57]
Last line is missing a "to" 

*******
We also need to check if that user's password matches up with the value in password_digest. Users must have both an account and know the password.

We validate password match by using a method called authenticate on our User model. We do not have write this method ourselves. Rather when we added the line of code to User:

**Comment by Sdcrouse** [comment]
Hi, it looks like you addressed the same issue twice on here.

**Comment by rrcobb** [comment]
Fixed in https://github.com/learn-co-curriculum/sinatra-password-security/commit/0f7f241c3662c1726bea7de275bc96fb2b6812dc , thanks for raising!
