### ISSUE TITLE
syntax issues with session[user_id]

### ISSUE THREAD

**Issue by LostnAustin** [learn-co-curriculum/sinatra-password-security#67]
The pre-written helper methods (application_controller.rb lines 64, 68): 
helpers do
		def logged_in?
			!!session[user_id]
		end

		def current_user
			User.find(session[user_id])
		end
	end

we need to modify these to session[:user_id] in order to access the user's session ID correctly. The above code will throw an error for the last spec test. modifying to session[:user_id] fixes issue. Wasn't part of the lesson directions or tests, so looked like potential syntax issue

**Comment by maxwellbenton** [comment]
Hi @LostnAustin,

Thank you for providing this feedback. We've updated this repository to use `session[:user_id]` which should resolve this issue going forward.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know.

Thank you for contributing to a Learn lesson!
